apiVersion: apps/v1
kind: Deployment
metadata:
  name: pzsd-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pzsd-bot
  template:
    metadata:
      labels:
        app: pzsd-bot
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: pzsd-bot
        image: ghcr.io/fiskenslakt/pzsd-bot:latest
        env:
        - name: TOKEN
          value: "INSECURE"
        - name: PGUSER
          value: "INSECURE"
        - name: PGPASSWORD
          value: "INSECURE"
        - name: PGHOST
          value: "INSECURE"
        - name: PGPORT
          value: "INSECURE"
        - name: PGDATABASE
          value: "pzsd_bot"
        - name: LOG_LEVEL
          value: "info"
        - name: PRIVATE_LEADERBOARD_KEY
          value: "HO-HO-HO"
        - name: PRIVATE_LEADERBOARD_ID
          value: "269893"
        - name: LEADERBOARD_CACHE_TTL_MINUTES
          value: 15
        - name: DAYS_IN_EVENT
          value: 12
        - name: EVENT_START_MONTH
          value: 12
        - name: EVENT_START_DAY
          value: 1
        resources:
          requests:
            cpu: "50m"  # 2.5% of a CPU
            memory: "64Mi"  # 3%-ish of a Gb
          limits:
            cpu: "250m"
            memory: "160Mi"
